### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by carreraprogrammer** [carreraprogrammer/space-travelers-hub#45]
https://github.com/carreraprogrammer/space-travelers-hub

We are a team of 2 people

**Comment by SajjadAhmad14** [comment]
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi team, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Improve 🙏

- [x] Please remove all the cards with the `Team3` prefix.


## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by carreraprogrammer** [comment]
Hi @SajjadAhmad14, thanks for the review. We'll do all the changes 😄

**Comment by m05e5** [comment]
Hi @SajjadAhmad14  and @carreraprogrammer , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] As mentioned by the previous reviewer please kindly remove the tasks concerning the Dragons since its only for teams of 3.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/37901469/204395912-e495187f-c2ce-4f07-9ffb-07d589b458cf.png">

- [ ] As a main requirement, kindly add the link to the Kanban board in the issue description 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ElsonOtake** [comment]
- [ ] Please paste the link to your Github project to the issue as required.

Click on `Projects``
<img width="1280" alt="Screen Shot 2022-11-28 at 9 11 28 PM" src="https://user-images.githubusercontent.com/47673311/204407232-183bbb52-d9d9-4871-9c90-c261acfe0bde.png">

Click on Projects (Classic). Reopen your project. 
<img width="1280" alt="Screen Shot 2022-11-28 at 9 11 45 PM" src="https://user-images.githubusercontent.com/47673311/204407419-9c591227-ba4e-413b-902b-cccd18c0bb36.png">

Open your reopened project and send the link as required.
<img width="1280" alt="Screen Shot 2022-11-28 at 9 06 21 PM" src="https://user-images.githubusercontent.com/47673311/204407557-a2bf9995-59f4-4fec-ac15-71b964b8899c.png">

On this kanban page remove the Team3 tasks

**Comment by ElsonOtake** [comment]
Hi @SajjadAhmad14 @carreraprogrammer , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Invalid code review request](https://media.makeameme.org/created/invalid-code-review-5f2c677fb9.jpg)

## Invalid Code Review Request

You have submitted a project, that didn't provide the link to the GitHub project. Check the tips in the previous comment.

<img width="813" alt="Screen Shot 2022-11-28 at 9 23 06 PM" src="https://user-images.githubusercontent.com/47673311/204408264-5a95d1ed-eaa8-44e0-acd9-ea0b6bdaf9e5.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
