### ISSUE TITLE
React & Redux group project: set up your Kanban board 

### ISSUE THREAD

**Issue by carreraprogrammer** [carreraprogrammer/space-travelers-hub#46]
This is the link to our project:

https://github.com/users/carreraprogrammer/projects/3 

We are on a 2 people team

**Comment by sja-thedude** [comment]
## Invalid Code Review Request ❌

Hi @carreraprogrammer, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't contain a valid kanban board link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by descholar-ceo** [comment]
Hi @carreraprogrammer && @david63011 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 All tasks are equally shared ✔️ 
👍🏽 All project's requirements are covered ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
